version: "3.3"
services:
  mysql-db:
    image: mysql:8.0
    stdin_open: true
    container_name: docker-db
    restart: always
    ports:
      - "3306:3306"
    command:
    - --sql_mode=
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE
    environment:
      MYSQL_DATABASE: testdb
      MYSQL_ROOT_PASSWORD: yourpassword
      MYSQL_USER: user
      MYSQL_PASSWORD: yourpassword
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro # local path : docker path
      - "/etc/timezone:/etc/timezone:ro" # datetime fix
      - "/etc/localtime:/etc/localtime:ro" # datetime fix
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
